### ISSUE TITLE
请问Pipe License类型？

### ISSUE THREAD

**Issue by rts-gordon** [88250/pipe#23]
Hi @88250 ：
  pipe这个新的blog平台很不错，但没有看到源代码的授权方式，请问License是什么类型的？可以在此基础上开发吗？

Good luck。

**Comment by rts-gordon** [comment]
@88250 看的云里雾里，简单的问：如果遵守木兰协议在Pipe上进行商业软件开发，是否要做到开源呢？谢谢。

**Comment by 88250** [comment]
不用开源。
