### ISSUE TITLE
服务器部署了pipe，首次进入首页，点击登陆，然后跳转失败

### ISSUE THREAD

**Issue by Huangsh17** [88250/pipe#24]
![E748E438-F64D-432c-A08A-F329C9E13973](https://user-images.githubusercontent.com/27496367/77837202-07062680-7199-11ea-912e-8494ee06a8b9.png)

**Comment by 88250** [comment]
配置过反向代理么？

**Comment by Huangsh17** [comment]
> 配置过直接使用docker部署的，没有配置代理

**Comment by Huangsh17** [comment]
直接使用docker部署的，没有用代理

**Comment by 88250** [comment]
docker logs 看下日志。
