### ISSUE TITLE
编译pipi最新版本的错误

### ISSUE THREAD

**Issue by rts-gordon** [88250/pipe#29]
1、下载最新版本，git clone https://github.com/88250/pipe.git
2、编译的错误，
go build -i -v
..\github.com\gin-gonic\gin\binding\default_validator.go:11:2: cannot find package "github.com/go-playground/validator/v10" in any of:
        D:\Program Files\Go\src\github.com\go-playground\validator\v10 (from $GOROOT)    
        D:\work\1CHCP\project\toolmaker\src\github.com\go-playground\validator\v10 (from 
$GOPATH)
..\github.com\88250\pipe\controller\feedctl.go:20:2: cannot find package "github.com/gorilla/feeds" in any of:
        D:\Program Files\Go\src\github.com\gorilla\feeds (from $GOROOT)
        D:\work\1CHCP\project\toolmaker\src\github.com\gorilla\feeds (from $GOPATH)      
..\github.com\88250\pipe\controller\sitemapctl.go:16:2: cannot find package "github.com/ikeikeikeike/go-sitemap-generator/stm" in any of:
        D:\Program Files\Go\src\github.com\ikeikeikeike\go-sitemap-generator\stm (from $GOROOT)
        D:\work\1CHCP\project\toolmaker\src\github.com\ikeikeikeike\go-sitemap-generator\stm (from $GOPATH)     
..\github.com\88250\pipe\controller\articlectl.go:27:2: cannot find package "github.com/vinta/pangu" in any of: 
        D:\Program Files\Go\src\github.com\vinta\pangu (from $GOROOT)
        D:\work\1CHCP\project\toolmaker\src\github.com\vinta\pangu (from $GOPATH)

3、单独获取依赖包也是错误的：
go get github.com\go-playground\validator\v10
package github.com/go-playground/validator/v10: cannot find package "github.com/go-playground/validator/v10" in 
any of:
        D:\Program Files\Go\src\github.com\go-playground\validator\v10 (from $GOROOT)
        D:\work\1CHCP\project\toolmaker\src\github.com\go-playground\validator\v10 (from $GOPATH)

请问该如何处理？谢谢了。

**Comment by 88250** [comment]
请通过 Go Modules 进行构建。

**Comment by rts-gordon** [comment]
Hi @88250 
环境：Windows 10版本，golang v1.14支持go mod；
问题：设置CGO_ENABLED=0出现错误：
go run main.go
opens database failed: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

后来改成CGO_ENABLED=1，出现错误：
go run main.go
github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%

我已经在windows10上安装SQLite，仍旧有问题。还是pipe不支持windows下编译运行？谢谢。

**Comment by 88250** [comment]
* 我这里没有单独安装 SQLite
* 支持 Windows 编译运行

**Comment by rts-gordon** [comment]
谢谢，那这个错误该如何解决啊? 本机没有安装MYSQL，打算使用SQLite3.

go run master.go 或者./pipe.exe 
D 2020/04/14 23:43:02 confs.go:183: configurations [&model.Configuration{Server:"http://localhost:5897", StaticServer:"http://localhost:5897", StaticResourceVersion:"1586060811337", LogLevel:"debug", ShowSQL:false, SessionSecret:"1TabWo9Y8jAhMVwqOPkVzMvFD9u1ISWn", SessionMaxAge:86400, RuntimeMode:"dev", SQLite:"C:\\Users\\Gordon/pipe.db", MySQL:"user:password@(localhost:3306)/pipe?charset=utf8mb4&parseTime=True&loc=Local&timeout=1s&readTimeout=16s&writeTimeout=16s", Port:"5897", AxiosBaseURL:"/api", MockServer:"http://localhost:8888"}]
D 2020/04/14 23:43:02 themes.go:43: loaded [7] themes
F 2020/04/14 23:43:02 db.go:44: opens database failed: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
exit status 1

**Comment by 88250** [comment]
```
Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```

看样子是编译的时候需要打开 `CGO_ENABLED=1`。
