### ISSUE TITLE
Upgrade vuefity to latest version 2.2.27

### ISSUE THREAD

**Issue by rts-gordon** [88250/pipe#35]
Hi @Vanessa219 , would you like to upgrade vuetify to version 2.2.27 with vditor? There are many new features in latest version. 

Thank you very much.

**Comment by Vanessa219** [comment]
vditor and vuetify are not related.

**Comment by rts-gordon** [comment]
OK. And would you like to upgrade vuetify to latest version only?

**Comment by Vanessa219** [comment]
Sorry, vuetify in the pipe is from the fork of vuetify. I made some modifications and I am afraid I cannot upgrade.

**Comment by rts-gordon** [comment]
Sure, there are too many modifications. Thank you.
