### ISSUE TITLE
自定义域名登录问题

### ISSUE THREAD

**Issue by Vanessa219** [88250/pipe#4]
版本：v1.8.8
域名：https://pipe.localvar.cn/
博客使用了另一个域名（nginx重定向）：https://blog.localvar.cn/

选择文章，点击编辑，github登录后回到原页面，再点击编辑，一直重重前述过程，其它管理员页面有同样问题。

大概调了以下程序，好像是 session 部分有问题，怀疑是一个域名下的cookie在另一个域名下读不出来。

**Comment by 88250** [comment]
只能在管理后台域上登录。
