### ISSUE TITLE
编译pipe的Docker镜像是报错，盼复

### ISSUE THREAD

**Issue by dourylee** [88250/pipe#47]
我在arm64v8设备上拉pipe的源码编译Docker镜像时一直报去下图错误，试着挂了梯子，但是还是报错，麻烦解答，非常感谢。
![Screenshot_20201013-084020__01](https://user-images.githubusercontent.com/22514904/95935976-08323480-0e07-11eb-93ff-5d8f4d600a97.jpg)

**Comment by 88250** [comment]
配置一下 goproxy，用 `https://goproxy.cn` 或者 `https://goproxy.io` 应该就好了。
